version: "2"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
      - UMASK_SET=022 #optional to set
    volumes:
      - ./config:/config
      - /mnt/movies:/movies
      - /mnt/tv:/tv
      - /mnt/anime:/anime
    ports:
      - 6767:6767
    restart: unless-stopped