version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
      #- RUN_OPTS=run options here #optional
    volumes:
      - /home/docker/jackett/data:/config
      - /home/docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped