version: '3.1'

services: 
  db:
    image: postgres
    container_name: postgres-mairelin
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    network_mode: bridge