version: "2"
services:
  pyload:
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo
    volumes:
      - /home/docker/pyload/config:/config
      - /sharedfolders/Downloads:/downloads
    ports:
      - 8181:8000
      - 7227:7227 #optional
    restart: unless-stopped