version: '3.1'

services: 
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: bridge
    

